CruGlobal/campus-contacts-web

app/assets/javascripts/angular/components/ministryViewLabel/ministryViewLabel.html
app/assets/javascripts/angular/components/multiselectList/multiselectList.html
app/assets/javascripts/angular/components/personProfile/personProfile.html
app/assets/javascripts/angular/unfound_translations.js

- Whitelist all labels that have i18n value in DB
- Translate label names if label has i18n value

MHP-344: Power to Change label translations

---

app/assets/javascripts/angular/components/personPage/personPage.component.js
app/assets/javascripts/angular/components/personPage/personPage.html
app/assets/javascripts/angular/components/personProfile/personProfile.component.js

Based off https://github.com/CruGlobal/missionhub-web/pull/2

 MHP-1012: Disable editing profile photos of other users

---

app/assets/javascripts/angular/components/personHistory/personHistory.service.js
app/assets/javascripts/angular/components/personHistory/personHistory.service.spec.js

Surveys store the org id on a different field.

MHP-1282: Fix survey filtering

---

app/assets/javascripts/angular/missionhubApp.config.js

@adammeyer You want this? I'm not really using the localhost API anymore.

Point development apiUrl at staging

---

app/assets/javascripts/angular/components/myPeopleDashboard/myPeopleDashboard.component.js
app/assets/javascripts/angular/components/myPeopleDashboard/myPeopleDashboard.service.js
app/assets/javascripts/angular/components/myPeopleDashboard/myPeopleDashboard.service.spec.js
app/assets/javascripts/angular/components/organizationOverviewPeople/organizationOverviewPeople.component.js
app/assets/javascripts/angular/components/organizationOverviewPeople/organizationOverviewPeople.html
app/assets/javascripts/angular/components/organizationOverviewPeople/organizationOverviewPeople.scss
app/assets/javascripts/angular/components/organizationOverviewPeople/organizationOverviewPeople.service.js
app/assets/javascripts/angular/components/organizationOverviewPeople/organizationOverviewPeople.service.spec.js

@nateemerson This is still throwing 500 errors. Assuming we still need to add `first_name,last_name,gender,followup_status` as `permitted_sort_params` in the API controller.

MHP-1656: Update sort params to match JSON API spec

---

app/assets/javascripts/angular/components/organizationBreadcrumbs/organizationBreadcrumbs.html

https://jira.cru.org/browse/MHP-1815

fix survey breadcrumbs

---

app/assets/javascripts/angular/components/peopleScreen/peopleScreen.component.js

This is throwing lots of errors https://rollbar.com/Cru/missionhub-web/items/649. I broke the connection to the parent component when implementing the survey responses refactor.

MHP-1813: Fix contact counts and undefined person errors

---

app/assets/javascripts/angular/components/ministryViewPerson/ministryViewPerson.html
app/assets/javascripts/angular/components/nav/nav.html
app/assets/javascripts/angular/components/organizationContactImport/organizationContactImportStep2.html
app/assets/javascripts/angular/components/personMultiselect/personMultiselect.html

All have been tested in Safari

remove unsafe JS links

---

app/assets/stylesheets/components/navigation.scss

I broke this with the survey question builder commit.  This resolves the issue.

tabs css fix

---

app/assets/javascripts/angular/components/surveyResponses/addSurveyResponseModal.html

https://jira.cru.org/browse/MHP-1932

MHP-1932: remove required attribute

---

app/assets/javascripts/angular/components/surveyOverview/surveyOverview.html
src/i18n/locales/en-US.js

https://jira.cru.org/browse/MHP-1826

survey preview button caption

---

app/assets/javascripts/angular/components/organizationContactImport/organizationContactImport.html
app/assets/javascripts/angular/components/organizationContactImport/organizationContactImportStep1.html
app/assets/javascripts/angular/components/organizationContactImport/organizationContactImportStep2.html
app/assets/javascripts/angular/components/organizationContactImport/organizationContactImportStep3.html
app/assets/javascripts/angular/components/organizationContactImport/organizationContactImportStep4.html
app/assets/javascripts/angular/components/publicSurvey/publicSurvey.component.js
app/assets/javascripts/angular/components/publicSurvey/publicSurvey.html
app/assets/javascripts/angular/components/surveyOverview/surveyOverview.scss
app/assets/javascripts/angular/components/surveyOverviewKeywordTab/keywordRequestModal.html
app/assets/javascripts/angular/components/surveyOverviewKeywordTab/surveyOverviewKeyword.html
app/assets/javascripts/angular/components/surveyOverviewQuestionsTab/surveyOverviewQuestions.html
app/assets/javascripts/angular/components/surveyOverviewSettingsTab/surveyOverviewSettings.html
app/assets/javascripts/angular/components/surveyResponses/addSurveyResponseModal.component.js
app/assets/javascripts/angular/components/surveyResponses/addSurveyResponseModal.html
app/assets/javascripts/angular/components/surveys/surveyForm.component.js
app/assets/javascripts/angular/components/surveys/surveyFormPublic.html
app/assets/javascripts/angular/components/surveys/surveyFormPublic.scss
app/assets/javascripts/angular/components/surveys/surveyFormUser.html
app/assets/javascripts/angular/missionhubApp.constants.js
app/assets/javascripts/angular/missionhubApp.routes.js
app/assets/javascripts/angular/missionhubApp.run.js
app/assets/stylesheets/bootstrap.scss
app/assets/stylesheets/components/dropdown.scss
app/assets/stylesheets/pivot_theme.scss
app/assets/stylesheets/variables/colors.scss
app/assets/stylesheets/variables/generateColors.scss
index.ejs
netlify.toml
src/i18n/locales/en-US.js

- Cleanup gray color naming
- Move color class generation to new file to prevent duplicate class creation
This can be demoed at https://deploy-preview-47--missionhub.netlify.com/s/19108 (or replace 19108 with your favorite survey id). Currently it isn't loading questions as that endpoint isn't public yet.

MHP-1639: Add public survey form

---

app/assets/javascripts/angular/components/surveyOverview/surveyOverview.scss
app/assets/javascripts/angular/components/surveyOverviewQuestionsTab/deleteQuestionConfirmModal.html
app/assets/javascripts/angular/components/surveyOverviewQuestionsTab/deleteQuestionConfirmModal.js
app/assets/javascripts/angular/components/surveyOverviewQuestionsTab/deleteQuestionConfirmModal.scss
app/assets/javascripts/angular/components/surveyOverviewQuestionsTab/predefinedQuestionsModal.component.js
app/assets/javascripts/angular/components/surveyOverviewQuestionsTab/predefinedQuestionsModal.html
app/assets/javascripts/angular/components/surveyOverviewQuestionsTab/surveyOverviewQuestions.component.js
app/assets/javascripts/angular/components/surveyOverviewQuestionsTab/surveyOverviewQuestions.html
app/assets/javascripts/angular/services/survey.service.js
src/i18n/locales/en-US.js

MHP-1637: add predefined question modal

---

app/assets/javascripts/angular/components/orgManagement/orgManagementEdit.html
app/assets/javascripts/angular/components/organizationContactImport/organizationContactImport.html
app/assets/javascripts/angular/components/organizationContactImport/organizationContactImportStep1.html
app/assets/javascripts/angular/components/organizationContactImport/organizationContactImportStep2.html
app/assets/javascripts/angular/components/organizationContactImport/organizationContactImportStep3.html
app/assets/javascripts/angular/components/organizationContactImport/organizationContactImportStep4.html
app/assets/javascripts/angular/components/surveyOverview/surveyOverview.scss
app/assets/javascripts/angular/components/surveyOverviewKeywordTab/keywordRequestModal.html
app/assets/javascripts/angular/components/surveyOverviewKeywordTab/surveyOverviewKeyword.html
app/assets/javascripts/angular/components/surveyOverviewQuestionsTab/deleteQuestionConfirmModal.html
app/assets/javascripts/angular/components/surveyOverviewQuestionsTab/predefinedQuestionsModal.html
app/assets/javascripts/angular/components/surveyOverviewQuestionsTab/surveyOverviewQuestions.html
app/assets/javascripts/angular/components/surveyOverviewSettingsTab/surveyOverviewSettings.html
app/assets/javascripts/angular/components/surveys/surveyFormUser.html
app/assets/stylesheets/variables/generateColors.scss

- Fix gray colors
Waiting for https://jira.cru.org/browse/MHP-1887 to be deployed.

Show predefined questions button

---

.eslintrc.json
app/assets/javascripts/angular/components/organizationOverviewSurveyResponses/organizationOverviewSurveyResponses.component.js
app/assets/javascripts/angular/components/organizationOverviewSurveyResponses/surveyResponsesModal.component.js
app/assets/javascripts/angular/components/organizationOverviewSurveyResponses/surveyResponsesModal.html
app/assets/javascripts/angular/services/localStorage.service.js

This is built off MHP-1674-survey-responses

MHP 1942 add new survey response model

---

app/assets/javascripts/angular/missionhubApp.config.js

It is currently hitting the prod api...

Fix new.missionhub.com environment

---

app/assets/javascripts/angular/missionhubApp.run.js
app/assets/javascripts/angular/services/httpProxy.service.js

Ok moved the logic into the API error handling for catching 401s and other errors related to token issues.

Mhp 2151 bearer token

---

app/assets/javascripts/angular/components/editGroupOrLabelAssignments/editGroupOrLabelAssignments.service.js
app/assets/javascripts/angular/components/myOrganizationsDashboard/myOrganizationsDashboard.service.js
app/assets/javascripts/angular/components/myPeopleDashboard/myPeopleDashboard.service.js
app/assets/javascripts/angular/components/myPeopleDashboard/myPeopleDashboard.service.spec.js
app/assets/javascripts/angular/components/organizationBreadcrumbs/organizationBreadcrumbs.component.js
app/assets/javascripts/angular/components/organizationOverviewSuborgs/organizationOverviewSuborgs.service.js
app/assets/javascripts/angular/missionhubApp.routes.js
app/assets/javascripts/angular/services/loggedInPerson.service.js
app/assets/javascripts/angular/services/organization.service.js
app/assets/javascripts/angular/services/organization.service.spec.js
src/i18n/locales/en-US.js

Hopefully there aren't any more places we need to do this. It's really hard to find API calls in this codebase...

MHP-1611: Add user_created: false filter to all organization endpoints.

---

app/assets/javascripts/angular/components/surveyOverviewQuestionsTab/surveyOverviewQuestions.component.js
app/assets/javascripts/angular/services/survey.service.js

Found a bug on production when trying to test Alex issue. if you want to remove a contact from the rule, it wont work.  Then also saw that when you delete a question answer, it doesnt delete both rules only the one on screen.  Added logic and fixed that.

MHP-2336: Fix survey question delete assigned person

---

app/assets/javascripts/angular/components/organizationSignatures/organizationSignaturesSign.component.js
app/assets/javascripts/angular/components/organizationSignatures/organizationSignaturesSign.html
src/i18n/locales/en-US.js

Logic added for showing accepted and declined messages.

Mhp 1668 signatures code and statement - accepted and decline messages

---

app/assets/javascripts/angular/missionhubApp.routes.js
app/assets/javascripts/angular/services/authentication.service.js
app/assets/javascripts/angular/services/loggedInPerson.service.js
app/assets/stylesheets/components/animations.scss
app/assets/stylesheets/main.scss
src/app.component.js
src/app.html
src/components/navigation/navHeader.component.js
src/components/navigation/navHeader.html
src/components/navigation/navHeader.scss

add fade animation
add authenticationService.loaded
make some position absolute to not overlap
fix broken class attribute

MHP-2384 fix navigation elements flashing

---

app/assets/javascripts/angular/components/organizationContactImport/organizationContactImportStep1.component.js

Small change ontop of original one.

send user to new survey created from import contacts

---

app/assets/javascripts/angular/services/authentication.service.js
src/components/authentication/mergeAccount.component.js

@OzzieOrca  this is an addon to the original branch alreayd merged to fix an issue for alex, please PR and let me know so i can push for her

force clearing of the key session when cancelling a merge

---

app/assets/javascripts/angular/missionhubApp.routes.js

Since this has been working and not throwing errors maybe it doesn't affect the config at all...

Fix access_token typo

---

app/assets/javascripts/angular/services/authentication.service.js

Mhp 2414 - currentState not initialized

---

index.ejs
package.json
src/.well-known/apple-app-site-association
src/.well-known/assetlinks.json
webpack.config.js
yarn.lock

Test links:
https://deploy-preview-149--missionhub.netlify.com/.well-known/apple-app-site-association
https://deploy-preview-149--missionhub.netlify.com/.well-known/assetlinks.json

MHP-2425: Add .well-known folder

---

app/assets/javascripts/angular/components/answerSheet/answerSheet.component.js
app/assets/javascripts/angular/components/answerSheet/answerSheet.html
app/assets/javascripts/angular/components/interaction/interaction.component.js
app/assets/javascripts/angular/components/interaction/interaction.html
app/assets/javascripts/angular/missionhubApp.module.js

It seems to import all of moment again. Figured this was easier than figuring that out.

Remove angular-moment

---

app/assets/javascripts/angular/services/httpProxy.service.js

Check that http error response has a data key before parsing error

Add null check to http error response data key

---

app/assets/javascripts/angular/components/personProfile/personProfile.html
app/assets/javascripts/angular/components/personProfile/personProfile.scss

I missed changing this to the new assigned people select when I switched to the new component name.

Fix-Assigned-To-On-Profile-Missing

---

app/assets/javascripts/angular/components/myPeopleDashboard/myPeopleDashboard.component.js
app/assets/javascripts/angular/components/myPeopleDashboard/myPeopleDashboard.service.js
app/assets/javascripts/angular/components/myPeopleDashboard/myPeopleDashboard.service.spec.js

I figured just making a check on the people's dashboard page for whether the user is using a mobile browser would be the best way to redirect. I'm not entirely sure if this covers all mobile browsers or if it's the best way of doing this. If there is a better method for checking let me know.

MHP-2890-Create-Landing-Page-For-Invite-Link

---

app/assets/javascripts/angular/components/dashboard/subnav/dashboard-subnav.html
app/assets/javascripts/angular/components/organizationOverview/organizationOverview.component.js
app/assets/javascripts/angular/components/organizationOverview/organizationOverview.html
app/assets/javascripts/angular/components/organizationOverview/organizationOverview.scss
app/assets/javascripts/angular/components/organizationalStats/organizationalStats.html
app/assets/javascripts/angular/components/peopleViewPerson/peopleViewPerson.scss
app/assets/javascripts/angular/components/statsHeader/statsHeader.html
app/assets/javascripts/angular/components/statsHeader/statsHeader.scss
app/assets/javascripts/angular/services/interactions.service.js
app/assets/stylesheets/components/navigation.scss
app/assets/stylesheets/variables/colors.scss
app/components/navigation/navHeader.html
app/components/navigation/navHeader.scss
src/communityInsights/components/RangePicker/__tests__/__snapshots__/RangePicker.tsx.snap
src/communityInsights/components/RangePicker/index.tsx
src/communityInsights/components/Table/__tests__/__snapshots__/Table.tsx.snap
src/communityInsights/components/Table/index.tsx
src/communityInsights/containers/Layout/__tests__/__snapshots__/Layout.tsx.snap
src/communityInsights/containers/Navigation/__tests__/__snapshots__/Navigation.tsx.snap
src/communityInsights/containers/Navigation/index.tsx

first-child and nth-child were giving an error about server side rendering issues, which wasn't affecting us but changing to the suggested type works just fine and eliminated the error.

MHP-2916-Update-Nav-For-Web

---

app/assets/javascripts/angular/components/organizationOverview/organizationOverview.html

Also hid the icons when on the root menu

Make Org Nav Collapse On Click

---

app/assets/javascripts/angular/components/dashboard/subnav/dashboard-subnav.html
app/assets/javascripts/angular/components/dashboard/subnav/dashboard-subnav.scss
app/assets/javascripts/angular/components/ministryViewGroup/ministryViewGroup.html
app/assets/javascripts/angular/components/myPeopleDashboard/myPeopleDashboard.html
app/assets/javascripts/angular/components/orgManagement/orgManagementEdit.html
app/assets/javascripts/angular/components/organizationOverview/organizationOverview.scss
app/assets/javascripts/angular/components/peopleViewPerson/peopleViewPerson.scss
app/assets/javascripts/angular/components/statsHeader/statsHeader.scss
app/assets/stylesheets/components/grid.scss

- Line up subnav
- Make tables shrink
- Hide reorder help on small devices
- Make Org Management responsive

Make tables more responsive

---

app/assets/javascripts/angular/components/peopleScreen/peopleScreen.html
app/assets/javascripts/angular/components/personPage/personPage.html
app/assets/javascripts/angular/components/personPage/personPage.scss
app/assets/javascripts/angular/components/personProfile/personProfile.scss

The history page textarea stills needs to be worked on.

Make Person Page Responsive

---

app/assets/javascripts/angular/components/peopleScreen/peopleScreen.html
app/assets/javascripts/angular/components/peopleScreen/peopleScreen.scss
app/assets/javascripts/angular/components/personPage/personPage.html
app/assets/javascripts/angular/components/personPage/personPage.scss

Cleanup person page responsive header

---

app/assets/images/icons/chevronLeft.svg
app/assets/javascripts/angular/components/organizationOverview/organizationOverview.html
app/assets/javascripts/angular/components/peopleScreen/peopleScreen.scss
app/assets/javascripts/angular/components/surveyResponses/surveyResponses.html
app/assets/javascripts/angular/components/surveyResponses/surveyResponses.scss

Make surveyResponses responsive

---

index.ejs

(the old beacon is being retired soon)

Update Helpscout Beacon

---

app/assets/javascripts/angular/components/myPeopleDashboard/myPeopleDashboard.component.js
app/assets/javascripts/angular/components/myPeopleDashboard/myPeopleDashboard.html
app/assets/javascripts/angular/components/myPeopleDashboard/myPeopleDashboard.service.js
src/i18n/locales/en-US.js

Same code as https://github.com/CruGlobal/missionhub-web/pull/422. This never actually got deployed. It went through code review and QA but was a commit on the `responsive-feature` branch that didn't get merged. Guess I merged the PR to the feature branch after it was already merged to master... 🤷‍♂ 
Just going to deploy it now.

MHP-3002: Suggest landscape

---

app/assets/javascripts/angular/missionhubApp.run.js

Missed this one. Should have searched for occurences of `mhub.cc` too.

Redirect from ccontacts.app if not on a public route

---

app/assets/javascripts/angular/components/organizationOverview/organizationOverview.html

Guess I copied and pasted this from somewhere else. There was a second paren involved 🤦 Thanks Angular for the help lol

Fix another paren

---

app/assets/javascripts/angular/missionhubApp.config.js
app/assets/javascripts/angular/services/facebookService.js
index.ejs

- Change dev environment to hit stage campus contacts api
- Upgrade FB SDK
- Change HelpScout Beacon ID
- Update The Key client ids

Add new Facebook App ID for campus contacts

---

.travis.yml

Since this is all on Amplify, it should be safe to delete these buckets after:
https://s3.console.aws.amazon.com/s3/buckets/cru-missionhub-web-prod/?region=us-east-1
https://s3.console.aws.amazon.com/s3/buckets/cru-missionhub-web-stage/?region=us-east-1

Remove S3 deployment

---

app/assets/javascripts/angular/services/httpProxy.service.js
app/assets/javascripts/angular/services/routes.service.js

- Fixes https://secure.helpscout.net/conversation/1270502642/482727/
- Merge params and extra config params to prevent them from overwriting each other in routesService.getPerson
- Include answer_sheets.survey on person history request

Fix includes on people tab for person page

---

.gitignore
bin/oneskyDownload.js
bin/oneskyUpload.js
src/i18n/locales/en-US.js

Do not advertise an unsupported feature.
[Helpscout](https://secure.helpscout.net/conversation/1865144154/754108/)

HS-754108 - Remove i wording

---

.github/workflows/node.js.yml

Switching conditional to look for master

Fixing GitHub Actions

---

amplify.yml

Migrate app to new dedicated AWS account

---

.github/workflows/update-staging.yml

Ensure PR's get deployed to staging if the label "On Staging" is added.
- Added on-staging GHA to merge PR into staging branch

Add workflow to update staging when PR has label On Staging

---

app/app.scss
app/components/navigation/navHeader.component.js
app/components/navigation/navHeader.html

Add a sunset banner to Campus Contacts. The names of the user's organizations are easy to pull from the API. I could not figure out how to extract more information because the API doesn't expose the Infobase id `importable_id` field that is in the database.
I didn't make the text into a translation because this app is going away.
[CC-15](https://jira.cru.org/browse/CC-15)

[CC-15] Add sunset banner
